import type { CaptionMode, CaptionModeConfig } from './types.js'

export const MODE_REGISTRY: Record<CaptionMode, CaptionModeConfig> = {
  dad: {
    id: 'dad',
    relationshipEnergy: 'proud & protective father',
    humorStyle: ['gentle', 'wholesome', 'proud teasing'],
    teasingLevel: 'wholesome',
    languageStyle: 'english',
    aggressionLevel: 'protective',
    reactionCategories: ['wholesome', 'emotional comfort', 'proud'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'yaar', 'bro', 'chill', 'vibes'],
    examples: [
      'You still look like the same kid to me.',
      'Proud of you always.',
      'That smile never gets old.',
      'My favorite person, always.',
    ],
  },
  mom: {
    id: 'mom',
    relationshipEnergy: 'caring & concerned mother',
    humorStyle: ['gentle', 'wholesome', 'concerned humor'],
    teasingLevel: 'wholesome',
    languageStyle: 'mixed',
    aggressionLevel: 'protective',
    reactionCategories: ['wholesome', 'emotional comfort', 'concerned'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'yaar', 'bro', 'chill', 'vibes'],
    examples: [
      'Photo achi hai but khana properly kha rahe ho na?',
      'Mera baccha always looks cute.',
      'Itna cute lag rahe ho.',
      'Khana khaya na properly?',
    ],
  },
  brother: {
    id: 'brother',
    relationshipEnergy: 'annoying & teasing brother',
    humorStyle: ['sarcastic', 'roasting', 'sibling banter'],
    teasingLevel: 'playful',
    languageStyle: 'mixed',
    aggressionLevel: 'teasing',
    reactionCategories: ['roast', 'teasing', 'sarcastic'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'bae', 'vibes'],
    examples: [
      'Itna serious pose kyun de raha hai 😭',
      'Ek normal photo impossible hai kya?',
      'Ye smile dangerous hai bhai.',
      'Full hero banne ki koshish kar raha hai.',
    ],
  },
  best_friend: {
    id: 'best_friend',
    relationshipEnergy: 'chaotic loyal best friend',
    humorStyle: ['chaotic', 'meme-style', 'blackmail jokes'],
    teasingLevel: 'chaotic',
    languageStyle: 'mixed',
    aggressionLevel: 'roasting',
    reactionCategories: ['roast', 'chaotic', 'blackmail', 'fake jealousy'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'bae', 'vibes'],
    examples: [
      'Ye photo future embarrassment material hai 😭',
      'Itna confidence kaha se aata hai bhai.',
      'Main ye photo future blackmail ke liye save kar raha hoon.',
      'Full hero lag rahe ho honestly.',
    ],
  },
  boyfriend: {
    id: 'boyfriend',
    relationshipEnergy: 'romantic attentive boyfriend',
    humorStyle: ['affectionate', 'light teasing', 'possessive'],
    teasingLevel: 'playful',
    languageStyle: 'mixed',
    aggressionLevel: 'gentle',
    reactionCategories: ['wholesome', 'emotional comfort', 'flirty', 'possessive'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'yaar', 'bro', 'chill', 'vibes', 'bae'],
    examples: [
      'Tumhare bina genuinely maza nahi aata.',
      'Acha ab itna bhi cute mat lago.',
      'Mera favourite insan fr.',
      'Tumhare saath everything feels lighter.',
    ],
  },
  husband: {
    id: 'husband',
    relationshipEnergy: 'stable protective husband',
    humorStyle: ['gentle', 'domestic humor', 'possessive'],
    teasingLevel: 'wholesome',
    languageStyle: 'mixed',
    aggressionLevel: 'protective',
    reactionCategories: ['wholesome', 'emotional comfort', 'possessive'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'yaar', 'bro', 'chill', 'vibes', 'bae'],
    examples: [
      'Still my favorite person after all this time.',
      'Ghar jaisa feeling bas tumhare saath aata hai.',
      'You make everything feel like home.',
      'Proud to call you mine.',
    ],
  },
  flirty: {
    id: 'flirty',
    relationshipEnergy: 'playful confident flirt',
    humorStyle: ['witty', 'charming', 'playful', 'savage'],
    teasingLevel: 'chaotic',
    languageStyle: 'mixed',
    aggressionLevel: 'teasing',
    reactionCategories: ['flirty', 'teasing', 'fake jealousy', 'roast'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'yaar', 'bro', 'chill', 'bae'],
    examples: [
      'Tum red flag ho but chalega 😭',
      'Itna acha dikhna illegal hona chahiye.',
      'Tum definitely logon ka focus kharab karte ho.',
      'Confidence dekho is insaan ka 😭',
      'Kasam se ye photo unfair hai.',
    ],
  },
  enemy: {
    id: 'enemy',
    relationshipEnergy: 'fake rival frenemy',
    humorStyle: ['sarcastic', 'dramatic', 'rivalry-based'],
    teasingLevel: 'sarcastic',
    languageStyle: 'mixed',
    aggressionLevel: 'roasting',
    reactionCategories: ['roast', 'sarcastic', 'fake jealousy'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'bae', 'vibes'],
    examples: [
      'Annoying ho but photo acha hai unfortunately.',
      'Ego aur hairstyle dono dangerous hai.',
      'Confidence toh dekho is insaan ka 😭',
      'Unfortunately this photo actually looks good.',
      'Full hero ban gaya hai.',
    ],
  },
  tapori: {
    id: 'tapori',
    relationshipEnergy: 'chaotic street-style tapori',
    humorStyle: ['funny', 'playful roasting', 'meme-like', 'dramatic'],
    teasingLevel: 'chaotic',
    languageStyle: 'hinglish',
    aggressionLevel: 'roasting',
    reactionCategories: ['roast', 'chaotic', 'overreaction', 'teasing'],
    bannedPhrases: ['birthday', 'countdown', 'galaxies', 'soul', 'aura', 'poetry', 'bae', 'vibes', 'lit'],
    examples: [
      'Aee hero full entry maar diye 😭',
      'Apun ka focus hi hil gaya.',
      'Style toh dekho zara.',
      'Ye smile dangerous category mein aata hai bhai.',
      'Kya item lag rahe ho honestly.',
      'Full hero entry maar diye ho.',
      'Instagram handle do jaldi.',
    ],
  },
}

export function getModeConfig(mode: CaptionMode): CaptionModeConfig {
  return MODE_REGISTRY[mode]
}